# ╔══════════════════════════════════════════════════════════════════════════╗
# ║                       数据分析报告流水线                                     ║
# ╚══════════════════════════════════════════════════════════════════════════╝

name: 数据分析报告
description: 数据分析与可视化报告自动生成
icon: "📊"

input:
  data_source:
    type: string
    description: 数据来源描述
    required: true
  metrics:
    type: string
    description: 关注指标
    required: false

steps:
  - skill: xlsx
    name: 数据分析
    prompt: |
      请对以下数据来源进行分析，生成 Excel 数据表：

      数据来源：{{input.data_source}}
      关注指标：{{input.metrics}}

      分析内容需包含：
      1. 数据概览与基础统计
      2. 关键指标的趋势分析
      3. 数据对比与排名
      4. 异常值标注

      请以结构清晰的 xlsx 格式输出。

  - skill: pdf
    name: 报告生成
    prompt: |
      基于以下数据分析结果，生成一份完整的数据分析报告（PDF）。

      分析数据：
      {{prev.output}}

      报告需包含：
      1. 摘要与核心发现
      2. 数据分析详情与图表描述
      3. 趋势解读与洞察
      4. 结论与建议

      请以专业的分析报告格式输出。

on_failure: stop
