# ╔══════════════════════════════════════════════════════════════════════════╗
# ║                         竞品对比工作流                                    ║
# ╚══════════════════════════════════════════════════════════════════════════╝

name: 竞品对比
description: 多家公司竞品对比分析，生成对比表格
icon: "⚖️"

input:
  companies:
    type: string
    description: 多个公司名称用逗号分隔
    required: true

steps:
  # ── 第一步：批量采集多家公司的财务与业务数据 ──
  - skill: stock-analyzer
    name: 数据采集
    prompt: |
      批量采集以下公司的核心数据，包括市值、营收、
      净利润、市盈率、市净率等可比指标。
      目标公司列表：{{input.companies}}

  # ── 第二步：生成结构化对比表格 ──
  - skill: xlsx
    name: 对比表格
    prompt: |
      将多家公司数据整理为横向对比表格，
      每行一家公司，每列一个指标，便于直观比较。
      数据来源：{{prev.output}}

on_failure: stop
