# ╔══════════════════════════════════════════════════════════════════════════╗
# ║                         社媒内容包工作流                                    ║
# ║         多平台社交媒体内容批量创作与配图                                       ║
# ╚══════════════════════════════════════════════════════════════════════════╝

name: 社媒内容包
description: 多平台社交媒体内容批量创作与配图
icon: "📱"

input:
  topic:
    type: string
    description: 内容主题
    required: true
  platforms:
    type: string
    description: 目标平台
    required: false
    default: "微信公众号,小红书"

steps:
  # ──────────────────────────────────────────────────────────────────────
  #  步骤一：根据主题与目标平台，批量生成社媒文案
  # ──────────────────────────────────────────────────────────────────────
  - skill: social-operator
    name: 内容创作
    prompt: |
      请围绕主题「{{input.topic}}」，为以下平台创作社交媒体内容：
      目标平台：{{input.platforms}}

      要求：
      - 根据每个平台的调性与用户习惯，分别输出适配的文案
      - 包含标题、正文、标签建议
      - 语言风格贴合平台受众，注重传播力与互动性

  # ──────────────────────────────────────────────────────────────────────
  #  步骤二：基于生成的文案内容，创作配套插图
  # ──────────────────────────────────────────────────────────────────────
  - skill: diagram
    name: 配图生成
    prompt: |
      根据以下社媒文案内容，为每个平台生成配套的插图方案：
      {{prev.output}}

      要求：
      - 配图风格与对应平台调性一致
      - 突出主题核心视觉元素
      - 输出图片描述与布局建议

on_failure: stop
