# ╔══════════════════════════════════════════════════════════════════════════╗
# ║                       数据监控日报工作流                                    ║
# ║           每日数据监控与异常预警报告                                         ║
# ╚══════════════════════════════════════════════════════════════════════════╝

name: 数据监控日报
description: 每日数据监控与异常预警报告
icon: "📉"

input:
  data_source:
    type: string
    description: 数据源描述
    required: true
  alert_threshold:
    type: string
    description: 预警阈值
    required: false

steps:
  # ──────────────────────────────────────────────────────────────────────
  #  步骤一：从指定数据源采集监控数据
  # ──────────────────────────────────────────────────────────────────────
  - skill: data-monitor
    name: 数据采集
    prompt: |
      从以下数据源采集最新的监控数据：
      数据源：{{input.data_source}}

      要求：
      - 采集关键指标的当日数据与历史趋势
      - 标记数据异常点与波动区间
      - 输出结构化的原始数据摘要

  # ──────────────────────────────────────────────────────────────────────
  #  步骤二：将采集数据整理为 Excel 并标注预警
  # ──────────────────────────────────────────────────────────────────────
  - skill: xlsx
    name: 数据处理
    prompt: |
      将以下监控数据处理为结构化的 Excel 表格：
      {{prev.output}}

      预警阈值：{{input.alert_threshold}}

      要求：
      - 按指标分类整理数据
      - 超过预警阈值的数据高亮标注
      - 包含同比、环比变化列
      - 生成数据汇总统计行

  # ──────────────────────────────────────────────────────────────────────
  #  步骤三：基于处理后的数据生成 PDF 日报
  # ──────────────────────────────────────────────────────────────────────
  - skill: pdf
    name: 日报生成
    prompt: |
      基于以下处理后的数据，生成每日监控报告 PDF：
      {{prev.output}}

      要求：
      - 包含数据概览、趋势图表、异常预警三个板块
      - 异常项需给出可能原因分析与建议措施
      - 报告格式清晰，适合管理层快速阅读

on_failure: stop
