# ╔══════════════════════════════════════════════════════════════════════════╗
# ║                         财务分析工作流                                    ║
# ╚══════════════════════════════════════════════════════════════════════════╝

name: 财务分析
description: 企业财务深度分析，从数据采集到专业报告
icon: "💹"

input:
  company:
    type: string
    description: 公司名称或股票代码
    required: true
  period:
    type: string
    description: 分析周期
    required: false
    default: latest

steps:
  # ── 第一步：采集目标公司的财务数据 ──
  - skill: stock-analyzer
    name: 数据采集
    prompt: |
      采集以下公司的核心财务数据，包括营收、净利润、
      毛利率、资产负债率、现金流等关键指标。
      目标公司：{{input.company}}

  # ── 第二步：对采集数据进行深度财务分析 ──
  - skill: financial-report
    name: 财务分析
    prompt: |
      基于已采集的财务数据，进行深度分析。
      分析维度：盈利能力、偿债能力、运营效率、成长性。
      数据来源：{{prev.output}}
      分析周期：{{input.period}}

  # ── 第三步：生成专业 PDF 财务报告 ──
  - skill: pdf
    name: 报告输出
    prompt: |
      将财务分析结果整理为专业 PDF 报告，
      包含图表、关键指标摘要和投资建议。
      分析内容：{{prev.output}}

on_failure: stop
