# ╔══════════════════════════════════════════════════════════════════════════╗
# ║                        合同审查流水线                                       ║
# ╚══════════════════════════════════════════════════════════════════════════╝

name: 合同审查
description: 合同文档智能审查与风险分析
icon: "📑"

input:
  contract_file:
    type: string
    description: 合同文件描述
    required: true
  focus_areas:
    type: string
    description: 重点审查领域
    required: false

steps:
  - skill: pdf
    name: 合同提取
    prompt: |
      请提取并解析以下合同文档的核心内容：

      合同信息：{{input.contract_file}}
      重点关注：{{input.focus_areas}}

      提取内容需包含：
      1. 合同基本信息（甲乙方、签订日期、有效期）
      2. 核心条款摘要
      3. 权利与义务条款
      4. 违约责任与赔偿条款
      5. 特殊约定与附加条件

  - skill: docx
    name: 审查报告
    prompt: |
      基于以下合同提取内容，生成一份合同审查报告（docx）。

      合同内容：
      {{prev.output}}

      审查报告需包含：
      1. 合同概要
      2. 条款合规性分析
      3. 潜在风险点识别与评级
      4. 权责对等性评估
      5. 修改建议与注意事项
      6. 审查结论

      请以专业法务审查报告的格式输出。

on_failure: stop
